### ISSUE TITLE
The data base will be null after changing pathways twice

### ISSUE THREAD

**Issue by thepunctuatedhorizon** [DevaDixon/Pathway_Guide#7]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(boolean, java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
                                                                             at edu.ccbcmd.pathwayguide.DatabaseWrapper.getSubPathwayClasses(DatabaseWrapper.java:24)
                                                                             at edu.ccbcmd.pathwayguide.CourseClassLoader.<init>(CourseClassLoader.java:74)
                                                                             at edu.ccbcmd.pathwayguide.chooseCompletedClasses.onCreate(chooseCompletedClasses.java:104)

I don't know why the database is not persistent.

**Comment by iewi** [comment]
Did the app crash with a NullPointerException before the database died? If it did, I'm thinking the database just closes on unhandled exception.

Whatever way, I can try reworking it so that the database opens and closes with each call. It's a bit more computationally expensive, and you'll have to instantiate a DatabaseWrapper Object, but it might solve problems like this.

**Comment by thepunctuatedhorizon** [comment]
I'm not sure.  I have tried to trace the problem with no success. I'll let you know if I find out more information.

**Comment by thepunctuatedhorizon** [comment]
It comes from screen orientations rotations.  I don't think the issue remains.  No new instances of it have come up in my testing.
